upstream forgecms_backend {
    server forgecms-a:8000;
    server forgecms-b:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 16m;

    location /static/uploads/ {
        alias /var/www/uploads/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://forgecms_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
